# Recitation0b-NumPy
## Contents
1. Installation
2. Initialization
3. Accessing and modifying data
4. Pivoting data
5. Combining data
6. Math operations

# 1. Installation
Generally NumPy is pre-installed on CoLab/AWS. You should first check if NumPy is available and its version.

To manually install Numpy, please follow the instructions below.

In [ ]:
# Check the installation of NumPy
!pip show numpy

# Install NumPy
!pip install numpy

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbprophet, f

In [ ]:
# Import the NumPy 
import numpy as np

# set the randomization seed
np.random.seed(0)

# 2. Initialization


Initialize new NumPy arrays

## a. Create an empty array/ zeros array/ ones array

In [ ]:
# initialize an empty array with size 2 x 2
empty_arr = np.empty((2, 2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

# initialize an all zero array with size 2 x 3
zeros_arr = np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

# initialize an all one array with size 4 x 2
ones_arr = np.ones((4, 2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

# return a new array of given shape and type, filled with fill_value
tens_arr = np.full((2,2), 10)
print("A filled array is \n", tens_arr, " with dimensions ", tens_arr.shape, "\n")

# return an array of zeros with the same shape and type as a given array
zeros_like_arr = np.zeros_like(ones_arr)
print("A zero like array is \n", zeros_like_arr, " with dimensions ", zeros_like_arr.shape, "\n")

# return an array of ones with the same shape and type as a given array
ones_like_arr = np.ones_like(zeros_arr)
print("A ones like array is \n", ones_like_arr, " with dimensions ", ones_like_arr.shape, "\n")

# Return a full array with the same shape and type as a given array.
full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, " with dimensions ", full_like_arr.shape, "\n")

An empty array is 
 [[5.e-324 5.e-324]
 [5.e-324 0.e+000]]  with dimensions  (2, 2) 

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 

A ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 

A filled array is 
 [[10 10]
 [10 10]]  with dimensions  (2, 2) 

A zero like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 

A ones like array is 
 [[1. 1. 1.]
 [1. 1. 1.]]  with dimensions  (2, 3) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]  with dimensions  (2, 3) 



## b. Create an array from existing data

In [ ]:
# initialize an array with the given list
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



In [ ]:
# initialize an array by loading data from a txt file
txt_arr = np.loadtxt(path_to_txt_file)

# initialize an array by loading data from a npy file
loaded_arr = np.load(path_to_npy_file)

## c. Numerical ranges

In [ ]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0, 3.0, num=5, endpoint=False)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

An array given range is 
 [0 1 2 3 4 5 6 7 8 9]  with dimensions  (10,) 

An evenly spaced array given range is 
 [2.  2.2 2.4 2.6 2.8]  with dimensions  (5,) 



## d. Create an array with random values

In [ ]:
# create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
uniform_rand_arr = np.random.rand(3,2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")

# return random integers from low (inclusive) to high (exclusive).
range_rand_int_arr = np.random.randint(5, size=(2, 4))
print("A random integer array from a range is \n", range_rand_int_arr, " with dimensions ", range_rand_int_arr.shape, "\n")

# For random samples from N(\mu, \sigma^2), use:
# sigma * np.random.randn(...) + mu
mu = 3
sigma =2.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)

A random array from a uniform distribution is 
 [[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]  with dimensions  (3, 2) 

A random integer array from a range is 
 [[4 0 0 4]
 [2 1 0 1]]  with dimensions  (2, 4) 

A random array from a gaussian distribution is 
 [[4.21078039 4.4478512  2.54604357 6.52551158]
 [2.06382077 3.68799579 0.59811347 3.94231744]]
with mu:  3
with sigma:  2.5
with dimensions  (2, 4)


# 3. Accessing and modifying data

## a. Indexing: Accessing values from Numpy Arrays

In [ ]:
n = np.random.rand(4, 5, 6) # see this as 4 batches, each containing 5 rows and 6 columns
n

array([[[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
         0.64589411],
        [0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
         0.52889492],
        [0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ,
         0.83261985],
        [0.77815675, 0.87001215, 0.97861834, 0.79915856, 0.46147936,
         0.78052918],
        [0.11827443, 0.63992102, 0.14335329, 0.94466892, 0.52184832,
         0.41466194]],

       [[0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
         0.6176355 ],
        [0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ,
         0.43703195],
        [0.6976312 , 0.06022547, 0.66676672, 0.67063787, 0.21038256,
         0.1289263 ],
        [0.31542835, 0.36371077, 0.57019677, 0.43860151, 0.98837384,
         0.10204481],
        [0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077,
         0.24442559]],

       [[0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
         0.368725

In [ ]:
n[1, 2, 3] # returns the element located in the forth column of third row of the second batch.

0.6706378696181594

## b. Slicing: Accessing subsections of Numpy Arrays based on Indices

In [ ]:
# slice along a batch
print(n[0, :, :]) # same as: n[0]

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]]


In [ ]:
print(n[0, 0:3, 0:4])

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.43758721 0.891773   0.96366276 0.38344152]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


In [ ]:
# slice along multiple batches
print(n[:, 3, 4]) # returns the elements in the 4th row and 5th column across all batches

[0.46147936 0.98837384 0.0641475  0.69947928]


### Slicing at Interval

In [ ]:
print(n[0::2]) # slices from index 0 to the end of the dimension at intervals of 2

[[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]
  [0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492]
  [0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985]
  [0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918]
  [0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]]

 [[0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517]
  [0.82099323 0.09710128 0.83794491 0.09609841 0.97645947 0.4686512 ]
  [0.97676109 0.60484552 0.73926358 0.03918779 0.28280696 0.12019656]
  [0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212]
  [0.56660145 0.26538949 0.52324805 0.09394051 0.5759465  0.9292962 ]]]


In [ ]:
print(n[0::2, 1:4, 1::2])

[[[0.891773   0.38344152 0.52889492]
  [0.92559664 0.0871293  0.83261985]
  [0.87001215 0.79915856 0.78052918]]

 [[0.09710128 0.09609841 0.4686512 ]
  [0.60484552 0.03918779 0.12019656]
  [0.11872772 0.41426299 0.69247212]]]


## c. Modifying Numpy Arrays

In [ ]:
n_copy = np.copy(n)

### Modify single values

In [ ]:
# check if values in the two arrays are the same before copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

n_copy[2, 4, 1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

True
False


In [ ]:
print(n_copy[2, 4, 1])

0.005


### Modifying multiple values

In [ ]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

Are the arrays the same before modification: [ True  True  True  True  True  True]
Before modifying values: [0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212]
After modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
Are the arrays the same after modification: [False False False False False False]


# 4.Pivoting data

## a. Reshaping Arrays
Array reshaping is an operation that changes the shape of an arrays whilst maintaining the same data in the array. 

For instance, reshaping from (3, 4, 5) -> (2, 5, 6) or from (3, 4, 5) -> (6, 10). A reshape operation is valid, so long as the product of the new shape specified matched the product of the old shape.

#### Reshaping within the same number of dimensions

In [ ]:
s = np.random.rand(3, 4, 5)
print(f"Original Shape: {s.shape}")

Original Shape: (3, 4, 5)


In [ ]:
s.size

60

In [ ]:
print(s)

[[[0.72525428 0.50132438 0.95608363 0.6439902  0.42385505]
  [0.60639321 0.0191932  0.30157482 0.66017354 0.29007761]
  [0.61801543 0.4287687  0.13547406 0.29828233 0.56996491]
  [0.59087276 0.57432525 0.65320082 0.65210327 0.43141844]]

 [[0.8965466  0.36756187 0.43586493 0.89192336 0.80619399]
  [0.70388858 0.10022689 0.91948261 0.7142413  0.99884701]
  [0.1494483  0.86812606 0.16249293 0.61555956 0.12381998]
  [0.84800823 0.80731896 0.56910074 0.4071833  0.069167  ]]

 [[0.69742877 0.45354268 0.7220556  0.86638233 0.97552151]
  [0.85580334 0.01171408 0.35997806 0.72999056 0.17162968]
  [0.52103661 0.05433799 0.19999652 0.01852179 0.7936977 ]
  [0.22392469 0.34535168 0.92808129 0.7044144  0.03183893]]]


In [ ]:
s1 = s.reshape(2, 6, 5)
print(f"Reshaped from s: {s1.shape}")

Reshaped from s: (2, 6, 5)


In [ ]:
print(s1)

[[[0.72525428 0.50132438 0.95608363 0.6439902  0.42385505]
  [0.60639321 0.0191932  0.30157482 0.66017354 0.29007761]
  [0.61801543 0.4287687  0.13547406 0.29828233 0.56996491]
  [0.59087276 0.57432525 0.65320082 0.65210327 0.43141844]
  [0.8965466  0.36756187 0.43586493 0.89192336 0.80619399]
  [0.70388858 0.10022689 0.91948261 0.7142413  0.99884701]]

 [[0.1494483  0.86812606 0.16249293 0.61555956 0.12381998]
  [0.84800823 0.80731896 0.56910074 0.4071833  0.069167  ]
  [0.69742877 0.45354268 0.7220556  0.86638233 0.97552151]
  [0.85580334 0.01171408 0.35997806 0.72999056 0.17162968]
  [0.52103661 0.05433799 0.19999652 0.01852179 0.7936977 ]
  [0.22392469 0.34535168 0.92808129 0.7044144  0.03183893]]]


### Reshaping to a different number of dimensions

In [ ]:
r = np.arange(120)

In [ ]:
print(f"Original shape: {r.shape}")

Original shape: (120,)


In [ ]:
print(r)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [ ]:
# (120,) -> (3, 4, 10)
r1 = r.reshape(3, 4, 10) # this can also be written as r.reshape((3, 4, 10))
print(f"Reshaped from r: {r1.shape}")

Reshaped from r: (3, 4, 10)


In [ ]:
print(r1)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [ ]:
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6, 20)
print(f"Reshaped from r1: {r2.shape}")

Reshaped from r1: (6, 20)


In [ ]:
print(r2)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]]


## b. Transposing Arrays
The transpose operation reverses the order of an array. It switches the rows to columns and vice versa. In a multi-dimensional array, the transpose operation moves the data from one axis to another in the order specified in the transpose method.

In [ ]:
w = np.arange(90).reshape((3, 5, 6))
w

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])

#### Transpose without specifying axes

In [ ]:
w1 = np.transpose(w)
w1

array([[[ 0, 30, 60],
        [ 6, 36, 66],
        [12, 42, 72],
        [18, 48, 78],
        [24, 54, 84]],

       [[ 1, 31, 61],
        [ 7, 37, 67],
        [13, 43, 73],
        [19, 49, 79],
        [25, 55, 85]],

       [[ 2, 32, 62],
        [ 8, 38, 68],
        [14, 44, 74],
        [20, 50, 80],
        [26, 56, 86]],

       [[ 3, 33, 63],
        [ 9, 39, 69],
        [15, 45, 75],
        [21, 51, 81],
        [27, 57, 87]],

       [[ 4, 34, 64],
        [10, 40, 70],
        [16, 46, 76],
        [22, 52, 82],
        [28, 58, 88]],

       [[ 5, 35, 65],
        [11, 41, 71],
        [17, 47, 77],
        [23, 53, 83],
        [29, 59, 89]]])

#### Transpose along specified axes

In [ ]:
w2 = np.transpose(w, axes=(0, 2, 1)) # 0, 1, 2
w2

array([[[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25],
        [ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27],
        [ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]],

       [[30, 36, 42, 48, 54],
        [31, 37, 43, 49, 55],
        [32, 38, 44, 50, 56],
        [33, 39, 45, 51, 57],
        [34, 40, 46, 52, 58],
        [35, 41, 47, 53, 59]],

       [[60, 66, 72, 78, 84],
        [61, 67, 73, 79, 85],
        [62, 68, 74, 80, 86],
        [63, 69, 75, 81, 87],
        [64, 70, 76, 82, 88],
        [65, 71, 77, 83, 89]]])

In [ ]:
w3 = np.transpose(w, axes=(1, 2, 0))
w3

array([[[ 0, 30, 60],
        [ 1, 31, 61],
        [ 2, 32, 62],
        [ 3, 33, 63],
        [ 4, 34, 64],
        [ 5, 35, 65]],

       [[ 6, 36, 66],
        [ 7, 37, 67],
        [ 8, 38, 68],
        [ 9, 39, 69],
        [10, 40, 70],
        [11, 41, 71]],

       [[12, 42, 72],
        [13, 43, 73],
        [14, 44, 74],
        [15, 45, 75],
        [16, 46, 76],
        [17, 47, 77]],

       [[18, 48, 78],
        [19, 49, 79],
        [20, 50, 80],
        [21, 51, 81],
        [22, 52, 82],
        [23, 53, 83]],

       [[24, 54, 84],
        [25, 55, 85],
        [26, 56, 86],
        [27, 57, 87],
        [28, 58, 88],
        [29, 59, 89]]])

## c. Flattening Arrays
The flatten operation in Numpy collapses arrays of multiple dimensions into one dimension.


Different orders can be specified when flattening Numpy Arrays. See examples below.

In [ ]:
k = np.random.rand(5, 6)

In [ ]:
k

array([[0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ,
        0.61396596],
       [0.5356328 , 0.58990998, 0.73012203, 0.311945  , 0.39822106,
        0.20984375],
       [0.18619301, 0.94437239, 0.7395508 , 0.49045881, 0.22741463,
        0.25435648],
       [0.05802916, 0.43441663, 0.31179588, 0.69634349, 0.37775184,
        0.17960368],
       [0.02467873, 0.06724963, 0.67939277, 0.45369684, 0.53657921,
        0.89667129]])

### Flattening Arrays along the row (default order)

In [ ]:
k1 = k.flatten() # all rows are stacked on each other into a 1D array.
k1

array([0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ,
       0.61396596, 0.5356328 , 0.58990998, 0.73012203, 0.311945  ,
       0.39822106, 0.20984375, 0.18619301, 0.94437239, 0.7395508 ,
       0.49045881, 0.22741463, 0.25435648, 0.05802916, 0.43441663,
       0.31179588, 0.69634349, 0.37775184, 0.17960368, 0.02467873,
       0.06724963, 0.67939277, 0.45369684, 0.53657921, 0.89667129])

In [ ]:
k1.shape

(30,)

### Flattening Arrays along the column

In [ ]:
k2= k.flatten('F') # forms a 1D array where elements in a column are listed before moving to the next column.
k2

array([0.16469416, 0.5356328 , 0.18619301, 0.05802916, 0.02467873,
       0.6214784 , 0.58990998, 0.94437239, 0.43441663, 0.06724963,
       0.57722859, 0.73012203, 0.7395508 , 0.31179588, 0.67939277,
       0.23789282, 0.311945  , 0.49045881, 0.69634349, 0.45369684,
       0.934214  , 0.39822106, 0.22741463, 0.37775184, 0.53657921,
       0.61396596, 0.20984375, 0.25435648, 0.17960368, 0.89667129])

### Flattening Arrays using Ravel

In [ ]:
k3 = k.ravel()
k3

array([0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ,
       0.61396596, 0.5356328 , 0.58990998, 0.73012203, 0.311945  ,
       0.39822106, 0.20984375, 0.18619301, 0.94437239, 0.7395508 ,
       0.49045881, 0.22741463, 0.25435648, 0.05802916, 0.43441663,
       0.31179588, 0.69634349, 0.37775184, 0.17960368, 0.02467873,
       0.06724963, 0.67939277, 0.45369684, 0.53657921, 0.89667129])

### Flattening Arrays using Numpy Reshape


In [ ]:
k4= k.reshape(-1)
k4

array([0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ,
       0.61396596, 0.5356328 , 0.58990998, 0.73012203, 0.311945  ,
       0.39822106, 0.20984375, 0.18619301, 0.94437239, 0.7395508 ,
       0.49045881, 0.22741463, 0.25435648, 0.05802916, 0.43441663,
       0.31179588, 0.69634349, 0.37775184, 0.17960368, 0.02467873,
       0.06724963, 0.67939277, 0.45369684, 0.53657921, 0.89667129])

### Flatten vs Ravel
Bothe functions take in the same kind of arguments and order to flatten can be specified in both arrays. The difference lies in how the result 1D arrays are are created in both cases.

In [ ]:
test = np.random.rand(4, 5)

In [ ]:
test_flatten = test.flatten()
test_ravel = test.ravel()

print(f"test_flatten: {test_flatten}")
print(f"test_ravel: {test_ravel}")

test_flatten: [0.99033895 0.21689698 0.6630782  0.26332238 0.020651   0.75837865
 0.32001715 0.38346389 0.58831711 0.83104846 0.62898184 0.87265066
 0.27354203 0.79804683 0.18563594 0.95279166 0.68748828 0.21550768
 0.94737059 0.73085581]
test_ravel: [0.99033895 0.21689698 0.6630782  0.26332238 0.020651   0.75837865
 0.32001715 0.38346389 0.58831711 0.83104846 0.62898184 0.87265066
 0.27354203 0.79804683 0.18563594 0.95279166 0.68748828 0.21550768
 0.94737059 0.73085581]


In [ ]:
test_flatten[0] = 5
print(f"Modified test_flatten: {test_flatten}")
print(f"Original Array: {test}")

Modified test_flatten: [5.         0.21689698 0.6630782  0.26332238 0.020651   0.75837865
 0.32001715 0.38346389 0.58831711 0.83104846 0.62898184 0.87265066
 0.27354203 0.79804683 0.18563594 0.95279166 0.68748828 0.21550768
 0.94737059 0.73085581]
Original Array: [[0.99033895 0.21689698 0.6630782  0.26332238 0.020651  ]
 [0.75837865 0.32001715 0.38346389 0.58831711 0.83104846]
 [0.62898184 0.87265066 0.27354203 0.79804683 0.18563594]
 [0.95279166 0.68748828 0.21550768 0.94737059 0.73085581]]


In [ ]:
test_ravel[0] = 5
print(f"Modified test_ravel: {test_ravel}")
print(f"Original Array: {test}")

Modified test_ravel: [5.         0.21689698 0.6630782  0.26332238 0.020651   0.75837865
 0.32001715 0.38346389 0.58831711 0.83104846 0.62898184 0.87265066
 0.27354203 0.79804683 0.18563594 0.95279166 0.68748828 0.21550768
 0.94737059 0.73085581]
Original Array: [[5.         0.21689698 0.6630782  0.26332238 0.020651  ]
 [0.75837865 0.32001715 0.38346389 0.58831711 0.83104846]
 [0.62898184 0.87265066 0.27354203 0.79804683 0.18563594]
 [0.95279166 0.68748828 0.21550768 0.94737059 0.73085581]]


## d. Squeezing & Expanding Arrays

### Squeezing Numpy Arrays

The squeeze operation allows reduction of numpy arrays axes by dropping an specified axis, so long as it is of **unit length**. The product of the shape (overall size of the array) remains the same.

In [ ]:
sq = np.random.rand(4, 1, 5)
print(f"Original Array: \n{sq}\n")
print(f"Shape of Original Array: {sq.shape}")

Original Array: 
[[[0.35561274 0.94043195 0.76532525 0.74866362 0.90371974]]

 [[0.08342244 0.55219247 0.58447607 0.96193638 0.29214753]]

 [[0.24082878 0.10029394 0.01642963 0.92952932 0.66991655]]

 [[0.78515291 0.28173011 0.58641017 0.06395527 0.4856276 ]]]

Shape of Original Array: (4, 1, 5)


In [ ]:
# transforms from (4, 1, 5) -> (4, 5)
sq1 = np.squeeze(sq)
print(f"Squeezed Array: \n {sq1}\n")
print(f"Shape of Squeezed Array: {sq1.shape}")

Squeezed Array: 
 [[0.35561274 0.94043195 0.76532525 0.74866362 0.90371974]
 [0.08342244 0.55219247 0.58447607 0.96193638 0.29214753]
 [0.24082878 0.10029394 0.01642963 0.92952932 0.66991655]
 [0.78515291 0.28173011 0.58641017 0.06395527 0.4856276 ]]

Shape of Squeezed Array: (4, 5)


#### Squeezing Multiple Axes
Multiple unit length axes can be squeezed as shown below

In [ ]:
q = np.random.rand(1, 4, 1, 5)
print(f"Original Array: \n {q}\n")
print(f"Shape of Original Array: {q.shape}")


Original Array: 
 [[[[0.36858461 0.13690027 0.82211773 0.18984791 0.51131898]]

  [[0.22431703 0.09784448 0.86219152 0.97291949 0.96083466]]

  [[0.9065555  0.77404733 0.33314515 0.08110139 0.40724117]]

  [[0.23223414 0.13248763 0.05342718 0.72559436 0.01142746]]]]

Shape of Original Array: (1, 4, 1, 5)


In [ ]:
q1 = np.squeeze(q)
print(f"Multiple Squeezed Array: \n {q1}\n")
print(f"Shape of Multiple Squeezed Array: {q1.shape}")

Multiple Squeezed Array: 
 [[0.36858461 0.13690027 0.82211773 0.18984791 0.51131898]
 [0.22431703 0.09784448 0.86219152 0.97291949 0.96083466]
 [0.9065555  0.77404733 0.33314515 0.08110139 0.40724117]
 [0.23223414 0.13248763 0.05342718 0.72559436 0.01142746]]

Shape of Multiple Squeezed Array: (4, 5)


#### Squeezing specified axes

In [ ]:
q2 = np.squeeze(q, axis=2)
print(f"Specified axis Squeezed Array: {q2}\n")
print(f"Shape of Specified axis Squeezed Array: {q2.shape}")

Specified axis Squeezed Array: [[[0.36858461 0.13690027 0.82211773 0.18984791 0.51131898]
  [0.22431703 0.09784448 0.86219152 0.97291949 0.96083466]
  [0.9065555  0.77404733 0.33314515 0.08110139 0.40724117]
  [0.23223414 0.13248763 0.05342718 0.72559436 0.01142746]]]

Shape of Specified axis Squeezed Array: (1, 4, 5)


### Unsqueezing (Expanding) Numpy Arrays
This is the direct opposite of squeezing. A new unit axis is inserted in specified position. Multiple unit axes can be inserted by using a tuple on the axis attribute of the `expand_dims` method.

In [ ]:
y = np.random.rand(4, 5)
print(f"Original Array: \n {y}\n")
print(f"Shape of Original Array: {y.shape}")

Original Array: 
 [[0.18115096 0.78854551 0.05684808 0.69699724 0.7786954 ]
 [0.77740756 0.25942256 0.37381314 0.58759964 0.2728219 ]
 [0.3708528  0.19705428 0.45985588 0.0446123  0.79979588]
 [0.07695645 0.51883515 0.3068101  0.57754295 0.95943334]]

Shape of Original Array: (4, 5)


In [ ]:
# transforms from (4, 5) -> (4, 1, 5)
y1 = np.expand_dims(y, axis=1)
print(f"Expanded Array: \n {y1}\n")
print(f"Shape of Expanded Array: {y1.shape}")

Expanded Array: 
 [[[0.18115096 0.78854551 0.05684808 0.69699724 0.7786954 ]]

 [[0.77740756 0.25942256 0.37381314 0.58759964 0.2728219 ]]

 [[0.3708528  0.19705428 0.45985588 0.0446123  0.79979588]]

 [[0.07695645 0.51883515 0.3068101  0.57754295 0.95943334]]]

Shape of Expanded Array: (4, 1, 5)


In [ ]:
# transforms from (4, 5) -> (1, 4, 1, 5)
y2 = np.expand_dims(y, axis=(0, 2))
print(f"Multi-axes Expanded Array: \n {y2}\n")
print(f"Shape of Multi-axes Expanded Array: {y2.shape}")

Multi-axes Expanded Array: 
 [[[[0.18115096 0.78854551 0.05684808 0.69699724 0.7786954 ]]

  [[0.77740756 0.25942256 0.37381314 0.58759964 0.2728219 ]]

  [[0.3708528  0.19705428 0.45985588 0.0446123  0.79979588]]

  [[0.07695645 0.51883515 0.3068101  0.57754295 0.95943334]]]]

Shape of Multi-axes Expanded Array: (1, 4, 1, 5)


# 5.Combining data

### 5a. Concatenation

A concatenation operation joins a sequence of arrays along an *existing* axis. All arrays must either have the same shape (except in the concatenating dimension) or be empty.

---



In [ ]:
# Concatenating 2-d Arrays

array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape)


Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 



ValueError: ignored

In [ ]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2) 
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)


Array 1 is 
 [[[0 1 0 1 1]
  [2 0 2 0 0]
  [0 2 1 2 2]
  [0 1 1 1 1]]

 [[0 1 0 0 1]
  [2 0 2 0 1]
  [1 2 0 1 1]
  [1 0 2 0 2]]

 [[2 0 2 0 0]
  [0 1 1 2 0]
  [0 1 0 1 2]
  [2 0 1 1 1]]]  with dimensions  (3, 4, 5) 

Array 2 is 
 [[[1 3 2 3 3]
  [2 2 3 0 2]
  [3 1 0 1 2]
  [0 3 0 2 0]]

 [[3 3 0 3 0]
  [0 0 0 2 3]
  [0 3 2 3 3]
  [1 1 1 0 1]]

 [[1 1 3 0 3]
  [1 2 0 1 2]
  [0 2 0 1 3]
  [2 2 1 0 3]]]  with dimensions  (3, 4, 5) 

Concatenated array 1 is 
 [[[0 1 0 1 1]
  [2 0 2 0 0]
  [0 2 1 2 2]
  [0 1 1 1 1]]

 [[0 1 0 0 1]
  [2 0 2 0 1]
  [1 2 0 1 1]
  [1 0 2 0 2]]

 [[2 0 2 0 0]
  [0 1 1 2 0]
  [0 1 0 1 2]
  [2 0 1 1 1]]

 [[1 3 2 3 3]
  [2 2 3 0 2]
  [3 1 0 1 2]
  [0 3 0 2 0]]

 [[3 3 0 3 0]
  [0 0 0 2 3]
  [0 3 2 3 3]
  [1 1 1 0 1]]

 [[1 1 3 0 3]
  [1 2 0 1 2]
  [0 2 0 1 3]
  [2 2 1 0 3]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)
Concatenated array 2 is 
 [[[0 1 0 1 1]
  [2 0 2 0 0]
  [0 2 1 2 2]
  [0 1 1 1 1]
  [1 3 2 3 3]
  [2 2 3 0 2]
  [3 1 0 1 2]
 

### 5b. Stacking

The stack operation joins a sequence of arrays along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension. All arrays need to be of the same size.  The stacked array has one more dimension than the input arrays.

In [ ]:
# Stacking 1-d Arrays

array1 = np.array([1, 2, 3])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([4, 5, 6])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 is \n", stacked_array1, " with dimensions ", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 is \n", stacked_array2, " with dimensions ", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = -1) 
print("Stacked array 3 is \n", stacked_array3, " with dimensions ", stacked_array3.shape)


Array 1 is 
 [1 2 3]  with dimensions  (3,) 

Array 2 is 
 [4 5 6]  with dimensions  (3,) 

Stacked array 1 is 
 [[1 2 3]
 [4 5 6]]  with dimensions  (2, 3)
Stacked array 2 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)
Stacked array 3 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)


In [ ]:

# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 has dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 has dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 has dimensions", stacked_array1.shape, "\n")

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 has dimensions", stacked_array2.shape, "\n")

stacked_array3 = np.stack((array1, array2), axis = 2) 
print("Stacked array 3 has dimensions", stacked_array3.shape, "\n")

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 has dimensions", stacked_array4.shape, "\n")



Array 1 has dimensions  (3, 4, 5) 

Array 2 has dimensions  (3, 4, 5) 

Stacked array 1 has dimensions (2, 3, 4, 5) 

Stacked array 2 has dimensions (3, 2, 4, 5) 

Stacked array 3 has dimensions (3, 4, 2, 5) 

Stacked array 4 has dimensions (3, 4, 5, 2) 



###5c. Repeat

The repeat operation repeats elements of an array. The number of repetitions for each element is broadcasted to fit the shape of the given axis. The axis parameter specifies along which axis to repeat values. By default, it uses the flattened input array, and return a flat output array.

In [ ]:

# Repeat in Numpy Arrays

original_array = np.array([[1,2],[3,4]])
print("Array is \n", original_array, " with dimensions ", original_array.shape, "\n")

repeated_array1 = np.repeat(original_array, 2)
print("Repeated array 1 is \n", repeated_array1, "\n\n", "and the dimensions of the repeated array 1 are: \n", repeated_array1.shape, "\n")

repeated_array2 = np.repeat(original_array, 3, axis=0)
print("Repeated array 2 is \n", repeated_array2, "\n\n", "and the dimensions of the repeated array 2 are: \n", repeated_array2.shape, "\n")

repeated_array3 = np.repeat(original_array, 3, axis=1)
print("Repeated array 3 is \n", repeated_array3, "\n\n", "and the dimensions of the repeated array 3 are: \n", repeated_array3.shape, "\n")

repeated_array4 = np.repeat(original_array, [2,3], axis=0)
print("Repeated array 4 is \n", repeated_array4, "\n\n", "and the dimensions of the repeated array 4 are: \n", repeated_array4.shape, "\n")


Array is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Repeated array 1 is 
 [1 1 2 2 3 3 4 4] 

 and the dimensions of the repeated array 1 are: 
 (8,) 

Repeated array 2 is 
 [[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 2 are: 
 (6, 2) 

Repeated array 3 is 
 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]] 

 and the dimensions of the repeated array 3 are: 
 (2, 6) 

Repeated array 4 is 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 4 are: 
 (5, 2) 



# 6. Math operations

In this section we will cover some commonly used mathematical operations
1. Broadcasting
1. Point-wise/element-wise operations
1. Redution operations
1. Comparison operations
1. Vector/Matrix operations

## a. Broadcasting

In [ ]:
# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

row_arr = np.random.rand(1,3)
print("A row array: \n", row_arr, " with dimensions ", row_arr.shape, "\n")
col_arr = np.random.rand(4,1)
print("A column array: \n", col_arr, " with dimensions ", col_arr.shape, "\n")

add_arr = row_arr + col_arr
print("row array + column array = ")
print(add_arr," with dimensions ", add_arr.shape, "\n")
mul_arr = row_arr * col_arr
print("row array * column array = ")
print(mul_arr," with dimensions ", mul_arr.shape, "\n")


A row array: 
 [[0.94466892 0.52184832 0.41466194]]  with dimensions  (1, 3) 

A column array: 
 [[0.26455561]
 [0.77423369]
 [0.45615033]
 [0.56843395]]  with dimensions  (4, 1) 

row array + column array = 
[[1.20922453 0.78640393 0.67921755]
 [1.71890261 1.29608201 1.18889563]
 [1.40081925 0.97799865 0.87081227]
 [1.51310287 1.09028227 0.98309589]]  with dimensions  (4, 3) 

row array * column array = 
[[0.24991746 0.1380579  0.10970114]
 [0.7313945  0.40403255 0.32104524]
 [0.43091104 0.23804129 0.18914818]
 [0.53698188 0.2966363  0.23570792]]  with dimensions  (4, 3) 



## b.Element-wise operations

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print("A random array1 : \n", rand_arr_1, " with dimensions ", rand_arr_1.shape, "\n")
rand_arr_2 = np.random.rand(2,3)
print("A random array2 : \n", rand_arr_2, " with dimensions ", rand_arr_2.shape, "\n")
scalar = 5.0

# Addition with Scalars
new_arr_1 = rand_arr_1 + scalar
print("random array1 + 5.0 =")
print(new_arr_1, "\n")

# Multiplication with Scalars
new_arr_2 = rand_arr_1 * scalar
print("random array1 * 5.0 =")
print(new_arr_2, "\n")

# Elementwise Addition of Arrays
new_arr_3 = rand_arr_1 + rand_arr_2
print("random array1 + random array2 =")
print(new_arr_3, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
new_arr_4 = rand_arr_1 * rand_arr_2
print("random array1 * random array2 =")
print(new_arr_4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
new_arr_5 = np.abs(-10*rand_arr_1)
print("abs (-10 * random array1) =")
print(new_arr_5, "\n")

# Square root value
new_arr_6 = np.sqrt(rand_arr_1)
print('sqrt(random array1) = \n', new_arr_6, "\n")

A random array1 : 
 [[0.0187898  0.6176355  0.61209572]
 [0.616934   0.94374808 0.6818203 ]]  with dimensions  (2, 3) 

A random array2 : 
 [[0.3595079  0.43703195 0.6976312 ]
 [0.06022547 0.66676672 0.67063787]]  with dimensions  (2, 3) 

random array1 + 5.0 =
[[5.0187898  5.6176355  5.61209572]
 [5.616934   5.94374808 5.6818203 ]] 

random array1 * 5.0 =
[[0.093949   3.08817749 3.06047861]
 [3.08466998 4.71874039 3.4091015 ]] 

random array1 + random array2 =
[[0.3782977  1.05466745 1.30972692]
 [0.67715947 1.61051479 1.35245817]] 

random array1 * random array2 =
[[0.00675508 0.26992645 0.42701707]
 [0.03715514 0.62925981 0.45725451]] 

abs (-10 * random array1) =
[[0.187898   6.17635497 6.12095723]
 [6.16933997 9.43748079 6.81820299]] 

sqrt(random array1) = 
 [[0.13707589 0.78589789 0.78236547]
 [0.78545146 0.97146697 0.82572411]] 



## c.Reduction

In [ ]:
rand_arr = np.random.rand(2,3)
print('random array: \n', rand_arr, "\n")

max_val = np.max(rand_arr)
print('Maximum value of array \n', max_val, "\n")
min_val = np.min(rand_arr)
print('Minimum value of array \n', min_val, "\n")

sum_val = np.sum(rand_arr)
print('Sum of array \n', sum_val, "\n")
max_idx = np.argmax(rand_arr, axis=0)
print('Maximum value\'s index of array along axis 0 \n', max_idx, "\n")
min_idx = np.argmin(rand_arr, axis=1)
print('Minimum value\'s index of array along axis 1 \n', min_idx, "\n")

mean_val = np.mean(rand_arr)
print('Mean value of array \n', mean_val, "\n")
std_val = np.std(rand_arr)
print('Standard deviation value of array \n', std_val, "\n")
norm_val = np.linalg.norm(rand_arr)
print('Norm value of array \n', norm_val, "\n")

random array: 
 [[0.21038256 0.1289263  0.31542835]
 [0.36371077 0.57019677 0.43860151]] 

Maximum value of array 
 0.5701967704178796 

Minimum value of array 
 0.1289262976548533 

Sum of array 
 2.0272462644757008 

Maximum value's index of array along axis 0 
 [1 1 1] 

Minimum value's index of array along axis 1 
 [1 0] 

Mean value of array 
 0.3378743774126168 

Standard deviation value of array 
 0.14445556227437842 

Norm value of array 
 0.9000883436106821 



## d.Comparision

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print('random array1: \n', rand_arr_1, '\n')
rand_arr_2 = np.random.rand(2,3)
print('random array2: \n', rand_arr_2, '\n')

# Element-wise Comparison Operations
greater_compare = rand_arr_1 > rand_arr_2
print('random array1 > random array2')
print(greater_compare, '\n')

less_compare = rand_arr_1 < rand_arr_2
print('random array1 < random array2')
print(less_compare, '\n')

not_equal_compare = rand_arr_1 != rand_arr_2
print('random array1 != random array2')
print(not_equal_compare, '\n')

# Combining reduction operations with boolean arrays
print("any values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(), "\n")

print("all values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).all(), "\n")

print("any values along first axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=0), "\n")

print("any values along second axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=1), "\n")

print("any values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).any(), "\n")

print("all values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).all(), "\n")

random array1: 
 [[0.98837384 0.10204481 0.20887676]
 [0.16130952 0.65310833 0.2532916 ]] 

random array2: 
 [[0.46631077 0.24442559 0.15896958]
 [0.11037514 0.65632959 0.13818295]] 

random array1 > random array2
[[ True False  True]
 [ True False  True]] 

random array1 < random array2
[[False  True False]
 [False  True False]] 

random array1 != random array2
[[ True  True  True]
 [ True  True  True]] 

any values for random array1 > random array2:
True 

all values for random array1 > random array2:
False 

any values along first axis for random array1 > random array2:
[ True False  True] 

any values along second axis for random array1 > random array2:
[ True  True] 

any values for random array1 != random array2:
True 

all values for random array1 != random array2:
True 



## e.Vector/Matrix operations

In [ ]:
# Vector x Vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1, 'with dimension ', array1.shape, '\n')
print('Array2 \n', array2, 'with dimension ', array2.shape, '\n')

matmul_arr = np.matmul(array1, array2)
another_arr = array1@array2
print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', matmul_arr)
print("Matmul of the two arrays can also be derived by using array1@array2 \n", another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, 'with dimension ', array3.shape, '\n')
print('Array4 \n', array4, 'with dimension ', array4.shape, '\n')

matmul_arr = np.matmul(array3, array4)
another_arr = array3@array4
print('Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) \n', matmul_arr)
print('Matmul of a vector and a matrix can also be derived by using array3@array4 \n', another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Matrix 

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1 \n', matrix1, 'with dimension ', matrix1.shape, '\n')
print('Matrix2 \n', matrix2, 'with dimension ', matrix2.shape, '\n')

matmul_mat = np.matmul(matrix1, matrix2)
print('Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) \n', matmul_mat)
print('Dimensions of resulting product: \n', matmul_mat.shape, "\n")

Array1 
 [-0.51080514 -1.18063218 -0.02818223] with dimension  (3,) 

Array2 
 [0.42833187 0.06651722 0.3024719 ] with dimension  (3,) 

Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 -0.3058508256835472
Matmul of the two arrays can also be derived by using array1@array2 
 -0.3058508256835472
Dimensions of resulting product: 
 ()
Array3 
 [[-0.63432209 -0.36274117 -0.67246045 -0.35955316]
 [-0.81314628 -1.7262826   0.17742614 -0.40178094]
 [-1.63019835  0.46278226 -0.90729836  0.0519454 ]] with dimension  (3, 4) 

Array4 
 [ 0.72909056  0.12898291  1.13940068 -1.23482582] with dimension  (4,) 

Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [-0.83148203 -0.11722929 -2.22679112]
Matmul of a vector and a matrix can also be derived by using array3@array4 
 [-0.83148203 -0.11722929 -2.22679112]
Dimensions of resulting product: 
 (3,)
Matrix1 
 [[3 0 0]
 [2 0 2]] with dimension  (2, 3) 

Matrix2 
 [[3 2]
 [2 3]
 [0 0]] with 

In [ ]:
rand_mat_1 = np.random.rand(4,2)
rand_mat_2 = np.random.rand(2,3)
print('Matrix1 \n', rand_mat_1, 'with dimension ', rand_mat_1.shape, '\n')
print('Matrix2 \n', rand_mat_2, 'with dimension ', rand_mat_2.shape, '\n')

# dot product
dot_mat = np.dot(rand_mat_1, rand_mat_2)
another_mat = rand_mat_1@rand_mat_2
print('Dot product of two matrices can be derived by using np.dot(mat1, mat2) \n', dot_mat)
print('Dot product of two matrices can also be derived by using mat1@mat2 \n', another_mat)
print('Dimensions of resulting product: \n', dot_mat.shape)

a = np.ones([9, 5, 7, 4])
b = np.ones([9, 5, 4, 3])
print('array1 \'s dimension ', a.shape, '\n')
print('array2 \'s dimension ', b.shape, '\n')

# matmul with multi-dimenstion arrays
c = np.matmul(a,b)
print('Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) \n')
print('Dimensions of resulting product: \n', c.shape)

Matrix1 
 [[0.82894003 0.00469548]
 [0.67781654 0.27000797]
 [0.73519402 0.96218855]
 [0.24875314 0.57615733]] with dimension  (4, 2) 

Matrix2 
 [[0.59204193 0.57225191 0.22308163]
 [0.95274901 0.44712538 0.84640867]] with dimension  (2, 3) 

Dot product of two matrices can be derived by using np.dot(mat1, mat2) 
 [[0.49524087 0.47646198 0.18889559]
 [0.65854564 0.50860922 0.37974551]
 [1.35198987 0.8509351  0.97841301]
 [0.69620562 0.39996403 0.54315682]]
Dot product of two matrices can also be derived by using mat1@mat2 
 [[0.49524087 0.47646198 0.18889559]
 [0.65854564 0.50860922 0.37974551]
 [1.35198987 0.8509351  0.97841301]
 [0.69620562 0.39996403 0.54315682]]
Dimensions of resulting product: 
 (4, 3)
array1 's dimension  (9, 5, 7, 4) 

array2 's dimension  (9, 5, 4, 3) 

Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) 

Dimensions of resulting product: 
 (9, 5, 7, 3)


###Tensordot

Understanding tensordot function will help you in writing succint code for your homeworks especially in Convolutional Neural Net assignment.

To give a brief overview: 
We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

In [ ]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print('A \'s dimension ', a.shape, '\n')
print('B \'s dimension ', b.shape, '\n')

# compute tensor dot product along specified axes.
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print("A⨂B =\n", c, ' with dimension', c.shape, '\n')

# this equals to 
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
print("tensor dot is equal to sum over certain dimensions.\n")
print(c==d)

A 's dimension  (3, 4, 5) 

B 's dimension  (4, 3, 2) 

A⨂B =
 [[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]  with dimension (5, 2) 

tensor dot is equal to sum over certain dimensions.

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
